- name: Download influxdata-archive_compat.key
  get_url:
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    dest: /tmp/influxdata-archive_compat.key

- name: Verify the checksum of the key file
  command: "sha256sum -c"
  args:
    chdir: /tmp
    stdin: "393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c  influxdata-archive_compat.key"
  register: checksum_result
  failed_when: "checksum_result.rc != 0"
  changed_when: false

- name: Convert the key to gpg format
  command: gpg --dearmor -o /tmp/influxdata-archive_compat.gpg /tmp/influxdata-archive_compat.key
  become: yes

- name: Move the gpg key to trusted.gpg.d
  command: mv /tmp/influxdata-archive_compat.gpg /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg
  become: yes

- name: Add InfluxData repository
  become: true
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main"
    state: present
    filename: "influxdata.list"

- name: Update apt cache
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install InfluxDB v2
  apt:
    name: influxdb2
    state: present

- name: Install InfluxDB v2 CLI
  apt:
    name: influxdb2-cli
    state: present

- name: Install Telegraf
  apt:
    name: telegraf
    state: present

- name: Copy get_telegraf_proccpu_json.sh to /opt/autoware/bin
  become: true
  copy:
    src: "{{ role_path }}/files/get_telegraf_proccpu_json.sh"
    dest: /opt/autoware/bin/get_telegraf_proccpu_json.sh
    owner: root
    group: root
    mode: "0755"

- name: Copy get_telegraf_procmem_json.sh to /opt/autoware/bin
  become: true
  copy:
    src: "{{ role_path }}/files/get_telegraf_procmem_json.sh"
    dest: /opt/autoware/bin/get_telegraf_procmem_json.sh
    owner: root
    group: root
    mode: "0755"

- name: Copy telegraf.conf to /opt/autoware/bin
  become: true
  copy:
    src: "{{ role_path }}/files/telegraf.conf"
    dest: /etc/telegraf/telegraf.conf
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify:
    - Restart telegraf

- name: Ensure telegraf is running and enabled
  systemd:
    name: telegraf
    enabled: true
    state: started
